import {text} from '@/domain/common';
import type {JunkTarget} from '@/domain/junk';

/**
 * Every disposable location rux knows about.
 *
 * Rules applied when adding an entry:
 *  - `risk: 'safe'` is reserved for data Windows or the tool itself regenerates
 *    on demand with no user-visible loss.
 *  - `minimumAgeDays` protects files still in use. Temp folders in particular
 *    hold installer state for in-flight operations, so recent files are skipped.
 *  - Locations that Windows expects to exist use `sweep: 'contents'`, which
 *    empties them without deleting the folder itself.
 */
export const JUNK_CATALOG: readonly JunkTarget[] = Object.freeze([
	{
		id: 'user-temp',
		category: 'user-temp',
		path: '%LOCALAPPDATA%\\Temp',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'user',
		description: text('junk.targets.userTemp'),
		minimumAgeDays: 1,
		extensions: null,
	},
	{
		id: 'windows-temp',
		category: 'system-temp',
		path: '%SystemRoot%\\Temp',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'administrator',
		description: text('junk.targets.windowsTemp'),
		minimumAgeDays: 1,
		extensions: null,
	},
	{
		id: 'windows-update-cache',
		category: 'windows-update',
		path: '%SystemRoot%\\SoftwareDistribution\\Download',
		sweep: 'contents',
		risk: 'review',
		elevation: 'administrator',
		description: text('junk.targets.windowsUpdateCache'),
		minimumAgeDays: 7,
		extensions: null,
	},
	{
		id: 'delivery-optimization',
		category: 'delivery-optimization',
		path: '%SystemRoot%\\SoftwareDistribution\\DeliveryOptimization',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'administrator',
		description: text('junk.targets.deliveryOptimization'),
		minimumAgeDays: 1,
		extensions: null,
	},
	{
		id: 'prefetch',
		category: 'prefetch',
		path: '%SystemRoot%\\Prefetch',
		sweep: 'contents',
		risk: 'review',
		elevation: 'administrator',
		description: text('junk.targets.prefetch'),
		minimumAgeDays: 30,
		extensions: ['.pf'],
	},
	{
		id: 'thumbnail-cache',
		category: 'thumbnail-cache',
		path: '%LOCALAPPDATA%\\Microsoft\\Windows\\Explorer',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'user',
		description: text('junk.targets.thumbnailCache'),
		minimumAgeDays: 0,
		extensions: ['.db'],
	},
	{
		id: 'inet-cache',
		category: 'icon-cache',
		path: '%LOCALAPPDATA%\\Microsoft\\Windows\\INetCache',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'user',
		description: text('junk.targets.inetCache'),
		minimumAgeDays: 1,
		extensions: null,
	},
	{
		id: 'error-reports-user',
		category: 'error-reports',
		path: '%LOCALAPPDATA%\\Microsoft\\Windows\\WER',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'user',
		description: text('junk.targets.errorReportsUser'),
		minimumAgeDays: 1,
		extensions: null,
	},
	{
		id: 'error-reports-machine',
		category: 'error-reports',
		path: '%ProgramData%\\Microsoft\\Windows\\WER',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'administrator',
		description: text('junk.targets.errorReportsMachine'),
		minimumAgeDays: 1,
		extensions: null,
	},
	{
		id: 'crash-dumps',
		category: 'crash-dumps',
		path: '%LOCALAPPDATA%\\CrashDumps',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'user',
		description: text('junk.targets.crashDumps'),
		minimumAgeDays: 1,
		extensions: null,
	},
	{
		id: 'memory-dump',
		category: 'crash-dumps',
		path: '%SystemRoot%\\MEMORY.DMP',
		sweep: 'entry',
		risk: 'review',
		elevation: 'administrator',
		description: text('junk.targets.memoryDump'),
		minimumAgeDays: 7,
		extensions: null,
	},
	{
		id: 'minidump',
		category: 'crash-dumps',
		path: '%SystemRoot%\\Minidump',
		sweep: 'contents',
		risk: 'review',
		elevation: 'administrator',
		description: text('junk.targets.minidump'),
		minimumAgeDays: 30,
		extensions: ['.dmp'],
	},
	{
		id: 'recycle-bin',
		category: 'recycle-bin',
		path: 'shell:RecycleBinFolder',
		sweep: 'recycle-bin',
		risk: 'review',
		elevation: 'user',
		description: text('junk.targets.recycleBin'),
		minimumAgeDays: 0,
		extensions: null,
	},
	{
		id: 'font-cache',
		category: 'font-cache',
		path: '%SystemRoot%\\ServiceProfiles\\LocalService\\AppData\\Local\\FontCache',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'administrator',
		description: text('junk.targets.fontCache'),
		minimumAgeDays: 1,
		extensions: null,
	},
	{
		id: 'cbs-logs',
		category: 'log-files',
		path: '%SystemRoot%\\Logs\\CBS',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'administrator',
		description: text('junk.targets.cbsLogs'),
		minimumAgeDays: 7,
		extensions: ['.log', '.cab'],
	},
	{
		id: 'dism-logs',
		category: 'log-files',
		path: '%SystemRoot%\\Logs\\DISM',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'administrator',
		description: text('junk.targets.dismLogs'),
		minimumAgeDays: 7,
		extensions: ['.log'],
	},
	{
		id: 'edge-cache',
		category: 'browser-cache',
		path: '%LOCALAPPDATA%\\Microsoft\\Edge\\User Data\\Default\\Cache',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'user',
		description: text('junk.targets.edgeCache'),
		minimumAgeDays: 0,
		extensions: null,
	},
	{
		id: 'chrome-cache',
		category: 'browser-cache',
		path: '%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Default\\Cache',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'user',
		description: text('junk.targets.chromeCache'),
		minimumAgeDays: 0,
		extensions: null,
	},
	{
		id: 'firefox-cache',
		category: 'browser-cache',
		path: '%LOCALAPPDATA%\\Mozilla\\Firefox\\Profiles',
		sweep: 'contents',
		risk: 'review',
		elevation: 'user',
		description: text('junk.targets.firefoxCache'),
		minimumAgeDays: 1,
		extensions: null,
	},
	{
		id: 'npm-cache',
		category: 'package-manager-cache',
		path: '%LOCALAPPDATA%\\npm-cache',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'user',
		description: text('junk.targets.npmCache'),
		minimumAgeDays: 7,
		extensions: null,
	},
	{
		id: 'nuget-cache',
		category: 'package-manager-cache',
		path: '%USERPROFILE%\\.nuget\\packages',
		sweep: 'contents',
		risk: 'review',
		elevation: 'user',
		description: text('junk.targets.nugetCache'),
		minimumAgeDays: 30,
		extensions: null,
	},
	{
		id: 'pip-cache',
		category: 'package-manager-cache',
		path: '%LOCALAPPDATA%\\pip\\Cache',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'user',
		description: text('junk.targets.pipCache'),
		minimumAgeDays: 7,
		extensions: null,
	},
	{
		id: 'yarn-cache',
		category: 'package-manager-cache',
		path: '%LOCALAPPDATA%\\Yarn\\Cache',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'user',
		description: text('junk.targets.yarnCache'),
		minimumAgeDays: 7,
		extensions: null,
	},
	{
		id: 'installer-downloads',
		category: 'installer-cache',
		path: '%LOCALAPPDATA%\\Downloaded Installations',
		sweep: 'contents',
		risk: 'safe',
		elevation: 'user',
		description: text('junk.targets.installerDownloads'),
		minimumAgeDays: 30,
		extensions: null,
	},
	{
		id: 'windows-old',
		category: 'installer-cache',
		path: '%SystemDrive%\\Windows.old',
		sweep: 'entry',
		risk: 'review',
		elevation: 'administrator',
		description: text('junk.targets.windowsOld'),
		minimumAgeDays: 10,
		extensions: null,
	},
]);
